/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootLayoutImport } from './routes/_root-layout'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as RootLayoutIndexImport } from './routes/_root-layout/index'
import { Route as RootLayoutProfileImport } from './routes/_root-layout/profile'
import { Route as AuthLayoutSignInImport } from './routes/_auth-layout/sign-in'

// Create/Update Routes

const RootLayoutRoute = RootLayoutImport.update({
  id: '/_root-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutProfileRoute = RootLayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RootLayoutRoute,
} as any)

const AuthLayoutSignInRoute = AuthLayoutSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_root-layout': {
      id: '/_root-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/sign-in': {
      id: '/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_root-layout/profile': {
      id: '/_root-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof RootLayoutProfileImport
      parentRoute: typeof RootLayoutImport
    }
    '/_root-layout/': {
      id: '/_root-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface RootLayoutRouteChildren {
  RootLayoutProfileRoute: typeof RootLayoutProfileRoute
  RootLayoutIndexRoute: typeof RootLayoutIndexRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutProfileRoute: RootLayoutProfileRoute,
  RootLayoutIndexRoute: RootLayoutIndexRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof RootLayoutRouteWithChildren
  '/sign-in': typeof AuthLayoutSignInRoute
  '/profile': typeof RootLayoutProfileRoute
  '/': typeof RootLayoutIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthLayoutRouteWithChildren
  '/sign-in': typeof AuthLayoutSignInRoute
  '/profile': typeof RootLayoutProfileRoute
  '/': typeof RootLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_root-layout': typeof RootLayoutRouteWithChildren
  '/_auth-layout/sign-in': typeof AuthLayoutSignInRoute
  '/_root-layout/profile': typeof RootLayoutProfileRoute
  '/_root-layout/': typeof RootLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/sign-in' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/sign-in' | '/profile' | '/'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/_root-layout'
    | '/_auth-layout/sign-in'
    | '/_root-layout/profile'
    | '/_root-layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  RootLayoutRoute: RootLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-layout",
        "/_root-layout"
      ]
    },
    "/_auth-layout": {
      "filePath": "_auth-layout.tsx",
      "children": [
        "/_auth-layout/sign-in"
      ]
    },
    "/_root-layout": {
      "filePath": "_root-layout.tsx",
      "children": [
        "/_root-layout/profile",
        "/_root-layout/"
      ]
    },
    "/_auth-layout/sign-in": {
      "filePath": "_auth-layout/sign-in.tsx",
      "parent": "/_auth-layout"
    },
    "/_root-layout/profile": {
      "filePath": "_root-layout/profile.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/": {
      "filePath": "_root-layout/index.tsx",
      "parent": "/_root-layout"
    }
  }
}
ROUTE_MANIFEST_END */
